# Generated by Django 5.0.1 on 2024-02-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("student_password", models.CharField(max_length=20)),
            ],
        ),
    ]
