# Generated by Django 5.0.1 on 2024-02-16 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_timetableentry_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
