# Generated by Django 5.0.1 on 2024-02-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_delete_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
