# Generated by Django 5.0.1 on 2024-02-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_faculty_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='faculties',
            field=models.ManyToManyField(to='app1.faculty'),
        ),
    ]
