# Generated by Django 5.0.1 on 2024-02-24 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_course_faculties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='faculties',
        ),
    ]
